all:
	make -C shell
	make -C utils
	make -C sbin

install:
	make -C shell install
	make -C utils install
	make -C sbin install

clean:
	make -C shell clean
	make -C utils clean
	make -C sbin clean

.PHONY: all install clean
